#!/bin/sh
#
# Spotlight search tool:
# shell script to refresh the index.
#
# Syntax:
#
#     spotlight-refresh [path ...]
#
# The default path is "/" which means everything on the local drive.
#
# To reindex a different volume, specify the path, such as:
#
#     spotlight-reindex /Volumes/MyHardDrive
#
# Cite: http://www.maclife.com/article/columns/terminal_101_rebuild_spotlight_index_fly
#
# Program: spotlight-refresh
# Version: 1.2.0
# Created: 2015-04-15
# Updated: 2016-02-09
# License: GPL
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
[[ $# -eq 0 ]] && args="/" || args="$@"
sudo mdutil -E "$args"
